apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todo
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '5000'
  name: todo-svc
  namespace: todo
spec:
  ports:
  - port: 5000
    # nodePort: 30080
    targetPort: 5000
  selector:
    app: todo
  # externalIPs:
  # - 80.11.12.10
  type: NodePort
# status:
#   loadBalancer: {}
